import React, { useEffect, useRef, useState } from "react";
import ReactDOM from 'react-dom';
import Head from 'next/head'
// import core
import { Button, Chip, Section, Divider, Grid, Header, Icon, IconButton, Stack, TextLink, Text, IMG, Backdrop, Card, Content, List, Footer, Drawer } from '../components/components';
import { Hero, Projects } from '../modules/modules'

// import markdown
import MarkdownIt from "markdown-it";
const md = new MarkdownIt();

// import api
import { fetchAPI, getStrapiURL } from "/api/strapi";


// fetch data
export async function getStaticProps({ }) {
  // get content from our api
  const header = await fetchAPI(`/header`);
  const content = await fetchAPI(`/imprint`);
  const footer = await fetchAPI(`/footer`);
  // return content from our api 
  return {
    props: { header, content, footer },
    revalidate: 600,
  };
}

export default function Imprint({ header, content, footer }) {

  return (
    <div className=''>
      <Head>
        <title>Impressum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      <Header data={header}  sticky styling="top-0 z-50 rounded-none" />

      {/* Content */}
    
      <div className='min-h-screen'>
        <Section spacing="large">
          <Text variant="d">{content.headline}</Text>
        </Section>
        <Section spacing="none" dangerouslySetInnerHTML={{ __html: md.render(content.content) }} />
      </div>

      {/* Footer */}

      <Footer data={footer} />
    </div>
  )
}

