import Head from 'next/head'
import { Button, Chip, Section, Divider, Grid, Header, Icon, IconButton, Stack, TextLink, Text, IMG, Backdrop } from '../core';
import { useState } from 'react';
import { useTheme } from 'next-themes'

// import api
import { fetchAPI, getStrapiURL } from "/api/strapi";


// fetch data
export async function getStaticProps({ }) {
  // get content from our api
  const header = await fetchAPI(`/header`);
  // return content from our api 
  return {
    props: { header },
    revalidate: 600,
  };
}

export default function Home(header) {

  const { theme, setTheme } = useTheme()
  const toggleTheme = () => setTheme(theme === 'light' ? 'dark' : 'light');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
      <Header data={header.header.Header} />
      </Section>
      <Section>
        <Button label="Theme" onClick={toggleTheme} />
        <div className='w-96 h-96 mt-24 bg-red-500 dark:bg-blue-500'/>
      </Section>

</div>
  )
}
