import Head from 'next/head'
import { Button } from '../components/button/button';
import { useState } from 'react';
import { useTheme } from 'next-themes'


export default function Home() {

  const { theme, setTheme } = useTheme()
  const toggleTheme = () => setTheme(theme === 'light' ? 'dark' : 'light');

  return (
    <div className='p-48'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Hello World</div>

      <Button label="Theme" onClick={toggleTheme} />
      <div className=' w-96 h-96 mt-48 bg-red-500 dark:bg-blue-500'/>


</div>
  )
}
