import React, { useEffect, useRef, useState } from "react";
import ReactDOM from 'react-dom';
import Head from 'next/head'
// import core
import { Section,  Header, Icon, Stack, Text, Footer } from '../components/components';
import {  } from '../modules/modules'

// import markdown
import MarkdownIt from "markdown-it";
const md = new MarkdownIt();

// import api
import { fetchAPI, getStrapiURL } from "/api/strapi";
import Src from "tailwindcss-global-dark";


// fetch data
export async function getStaticProps({ }) {
  // get content from our api
  const header = await fetchAPI(`/header`);
  const content = await fetchAPI(`/contact`);
  const footer = await fetchAPI(`/footer`);
  // return content from our api 
  return {
    props: { header, content, footer },
    revalidate: 600,
  };
}

export default function Contact({ header, content, footer }) {

  return (
    <div className=''>
      <Head>
        <title>Kontakt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      <Header data={header}  sticky styling="top-0 z-50 rounded-none" />

      {/* Content */}
    
      <div className='min-h-screen p-6'>
        <Section spacing="large">
          <Text variant="d" styling="max-w-960">{content.headline}</Text>
          <Text variant="b" styling="max-w-480">{content.text}</Text>
          <Stack orientation="horizontal" gap="4" styling="mt-8">
            <Text variant="h6">{content.contact}</Text>
            <Icon icon="arrow-right" size="large" styling="self-end"/>
          </Stack>
        </Section>
      </div>

      {/* Footer */}

      <Footer data={footer} />
    </div>
  )
}

