import Head from 'next/head'
import { Button, Chip, Section, Divider, Grid, Header, Icon, IconButton, Stack, TextLink, Text, Image, Backdrop } from '../core';
import Split from 'react-split'
import { useState } from 'react';
// import theme
import { useTheme } from 'next-themes'



const placeholder = `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.`

export default function Playground() {

  const [collapsedIndex, setCollapsedIndex] = useState(1);

  const { theme, setTheme } = useTheme()
  const toggleTheme = () => setTheme(theme === 'light' ? 'dark' : 'light');

  return (
    <div className=' bg-black text-white'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section size="full" spacing="none" styling="h-screen p-12 hidden xl:flex">
        <Split className='h-full w-full flex bg-white border-4'
          direction="horizontal"
          sizes={[99, 1]}
          expandToMin={true}
          minSize={100}
          gutterSize={4}
          snapOffset={100}
          collapsed={collapsedIndex}
        >
          <div className="relative bg-black p-12 text-h1 overflow-hidden">
          Es ist nie zu spät → Versuch mal was neues
          </div>
          <div className="bg-black overflow-hidden">
          <Image
          variant="flex"
          src="https://images.unsplash.com/photo-1604076913837-52ab5629fba9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80"
          styling="p-12"
          backdropcolor="black"
          backdropopacity="50"
          >
            <div className='relative z-30'>
              <div className='text-h3 text-white w-96'>Es ist nie zu spät → Versuch mal was neues</div>
              <div className='text-body text-white mt-3 w-96'>{placeholder}</div>
            </div>
            { collapsedIndex == 1
            ? <IconButton icon="plus" variant="contained" color="secondary" onClick={() => setCollapsedIndex(0)} styling="absolute z-30 bottom-3 left-3" />
            : <IconButton icon="minus" variant="contained" color="secondary" onClick={() => setCollapsedIndex(1)} styling="absolute z-30 bottom-3 left-3" /> 
            }
           

          </Image>
          </div>

        </Split>          
      </Section>

      <Section>
      {theme === 'light' && <IconButton styling="ml-12px" onClick={toggleTheme} icon="moon" color="primary" variant="ghost" />}
      {theme === 'dark' && <IconButton styling="ml-12px" onClick={toggleTheme} icon="sun" color="primary" variant="ghost" />}
      </Section>

      <Section size="large" spacing="large" styling="">
        <Grid cols="2" gap="8">
        <Image
          variant="flex"
          src="https://images.unsplash.com/photo-1550275994-cdc89cd1948f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8bmVvbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60"
        />   
        <div className="text-white"> 
            <Text variant="h6">Lorem Ipsum</Text>
            <Text variant="b2">{placeholder}</Text>
            <Text variant="b2">{placeholder}</Text>
        </div>
        </Grid>
      </Section>

      <Section size="full" spacing="none" styling="h-screen p-12 xl:hidden">
        <div className='h-full w-full flex bg-white border-4'>
          <div className="relative bg-black p-12 text-h1 overflow-hidden">
          Es ist nie zu spät → Versuch mal was neues
            <div className='text-caption p-4 absolute bottom-8 right-4 w-96 border-l-2 text-white hidden xl:block'>{placeholder}</div>
            <Icon icon="minimize-2" size="12" styling="absolute left-8 bottom-8 hidden xl:block"/>
          </div>
        </div>          
      </Section>

      <Section size="medium" styling="text-center">
      <Text variant="h1">Headline 1</Text>
      <Text variant="h2">Headline 2</Text>
      <Text variant="h3">Headline 3</Text>
      <Text variant="h4">Headline 4</Text>
      <Text variant="h5">Headline 5</Text>
      <Text variant="h6">Headline 6</Text>
      <Text variant="b">{placeholder}</Text>
      <Text variant="b2">{placeholder}</Text>
      <Text variant="c">{placeholder}</Text>
      </Section>


    </div>
  )
}
