import React, { useEffect, useRef, useState } from "react";
import ReactDOM from 'react-dom';
import Head from 'next/head'
// import core
import { Section, Grid, Stack, Header, Text, Footer } from '../components/components';
import { Hero, ContentBlock, Projects } from '../modules/modules'

// import markdown
import MarkdownIt from "markdown-it";
const md = new MarkdownIt();

// import api
import { fetchAPI, getStrapiURL } from "/api/strapi";
import { Channel } from "@storybook/addons";

// fetch data
export async function getStaticProps({ }) {
  // get content from our api
  const header = await fetchAPI(`/header`);
  const content = await fetchAPI(`/services`);
  const projects = await fetchAPI(`/projects`);
  const footer = await fetchAPI(`/footer`);
  // return content from our api 
  return {
    props: { header, content, projects, footer },
    revalidate: 600,
  };
}

export default function Services({ header, content, projects, footer }) {
  console.log(content.services);
  return (
    <div className=''>
      <Head>
        <title>Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      <Header data={header}  sticky styling="top-0 z-50 rounded-none" />
      <Hero data={content.hero} />

      {/* Content */}

      <div className='min-h-screen p-6'>
      <Section spacing="large">
        <Grid  lgcols="3">
          {content.solutions.map (data =>
            <div className="border-l-2 border-black dark:border-white p-6 markdown" dangerouslySetInnerHTML={{ __html: md.render(data.content) }} />
          )}
        </Grid>
      </Section>
      <ContentBlock data={content.contentBlocks[0]} />
      <ContentBlock data={content.contentBlocks[1]} swapped/>
      <Section>
      <Text variant="h1">{content.projects.headline}</Text>
      </Section>

      </div>

      <Projects data={projects} id="2"/>

      {/* Footer */}

      <Footer data={footer} />
    </div>
  )
}

